config/routes.rb
Rails.application.routes.draw do

          # Home #
  root 'pages#home'
          # About #
  get 'about', to:'pages#about'
          # Articles #
  resources :articles
          # Sign up #
  get 'signup', to: 'users#signup'
  resources :users, except: [:new]
          # Log in #
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
            # Categories #
  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :tittle, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }


end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true,
                  uniqueness: { case_sensitive: false },
                  length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username, presence: true, 
                    uniqueness: { case_sensitive: false },
                    length: { minimum:3, maximum:25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum:105 }, 
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
    
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be login."
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def show
    #byebug
  end

  def new
    @article = Article.new
  end
  def create
    byebug
    #render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    if @article.destroy
      flash[:notice] = "Article was delete successfully."
      redirect_to articles_path
    end
  end
  
  private 
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:tittle, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end
  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with the login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end
  
  
  def signup
    @user = User.new
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully edited."
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha blog #{@user.username}, you have successfully signup."
      redirect_to articles_path
    else
      render 'signup'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Accound and all asociated articles successfully deleted."
    redirect_to articles_path
  end
  
  
  private 
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, user_path(article.user)%>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div> 
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.tittle, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
</div> 

app/views/articles/_form.html.erb
<%=render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f|%>
  <div class="form-group">
    <%= f.label :tittle, class: "form-label" %>
    <%= f.text_field :tittle, class:  "form-control", placeholder: "Enter title"%>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, rows: 6, class:  "form-control", placeholder: "Enter description"%>
  </div>
  <div class="form-group">
    <%= f.label :category, class: "form-label" %>
    <div class=""> 
      <%= f.collection_select(:category_ids, Category.all, :id, :name,
      { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select rounded" }) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-outline-primary btn-lg"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Edit article
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to article listing ]', articles_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>Articles</h1>
          <span class="subheading">listing</span>
        </div>
      </div>
    </div>
  </div>
</header>

<%= render 'layouts/msg'%>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Create article
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to article listing ]', articles_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>
<%= render 'layouts/msg'%>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= @article.user.username %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div> 
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to @article.tittle, article_path(@article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(@article.description, length: 100) %></p>
          <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to article listing ]', articles_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %> 

app/views/categories/_form.html.erb
<%=render 'shared/errors', obj: @category %>

<%= form_with(model: @category, local: true) do |f|%>
  <div class="form-group">
    <%= f.label :name, 'Category name', class: "form-label" %>
    <%= f.text_field :name, class:  "form-control", placeholder: "Enter name"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-outline-primary btn-lg"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<%= render 'layouts/msg'%>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Edit new category
        </div>
        <div class="card-body">  

          <%= render 'form' %>       
          
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to categories listing ]', categories_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<%= render 'layouts/msg'%>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-5 mt-2">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Categories
        </div>
      </div>
    </div>
  </div>
</div>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to category.name, category_path(category), class: "text-success" %>
            </h5>
            <p class="card-text"><%= pluralize(category.articles.count, 'article') %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div> 

app/views/categories/new.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<%= render 'layouts/msg'%>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Create new category
        </div>
        <div class="card-body">          
          <%=render 'shared/errors', obj: @category %>

          <%= form_with(model: @category, local: true) do |f|%>
            <div class="form-group">
              <%= f.label :name, 'Category name', class: "form-label" %>
              <%= f.text_field :name, class:  "form-control", placeholder: "Enter name"%>
            </div>
            <div class="form-group">
              <%= f.submit class: "btn btn-outline-primary btn-lg"%>
            </div>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Cancel and return to categories listing ]', articles_path %> </small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<div class="container">
<%= render 'layouts/msg'%>
    <div class="row justify-content-md-center">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= @category.name %></h5>
          </div>
          <% if logged_in? && current_user.admin? %>
            <div class="card-footer text-muted">
              <%= link_to "Edit", edit_category_path(@category), class: "btn btn-outline-info" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            Articles
          </div>
        </div>
      </div>
    </div>

  <div class="row justify-content-md-center">
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
  <%= render 'articles/article'%>
  <div class="row justify-content-md-center">
    <div class="flickr_pagination mb-4">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to 'Emilio Galindo', 'https//:linkedin.com/in/galindo-hayashi', class: "text-white" %></small>
    </div>
  </footer>

app/views/layouts/_msg.html.erb
<div class="container">
  <% flash.each do |k, msg|%>
    
    <div class="alert alert-<%= k == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg%>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    
    <%= link_to 'Alpha Blog', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarCategoriesDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarCategoriesDropdownMenuLink">
              <%= link_to 'Categories', categories_path, class: "dropdown-item" %>
              <% if logged_in? && current_user.admin? %>
                <%= link_to 'Create new category', new_category_path, class: "dropdown-item" %>    
              <% end %>
            </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Articles', articles_path, class: "dropdown-item" %>
            <% if logged_in?%>
              <%= link_to 'Create new article', new_article_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="profileDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="profileDropdownMenu">
              <%= link_to 'View your profile', user_path(current_user), class: "dropdown-item" %>
              <%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Log out', login_path, class: "dropdown-item", method: :delete %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/navbar'%>

    <div id="page-content">
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image:url(<%= asset_path 'articles-bg.jpg' %>); min-height: 100%; height: 100%;">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>About</h1>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/pages/home.html.erb
<!-- Page Header -->
<header class="masthead" style="background-image:url(<%= asset_path 'home-bg.jpg' %>); min-height: 100%; height: 100%;">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Alpha Blog</h1>
          <span class="subheading">Emilio Galindo Hayashi</span>
          <%= link_to 'Sign up!', signup_path, class: 'btn btn-primary float-center btn-lg mt-4' %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="alert-heading">The folowing errors prevented the <%= obj.class.name.downcase %> from saving.</h4>
    <hr>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg%></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Edit your profile
        </div>
        <div class="card-body">
          <%= render 'form' %>
          <%= link_to "Delete profile", user_path(@user), class: "btn btn-outline-danger btn-lg", method: :delete, data: { confirm: "Are you sure?" } %> 
        </div>
        <div class="card-footer text-muted">
          <small><%= link_to '[ Already have an account? ]', articles_path %> </small>
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/users/index.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" ></div>
</header>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-5 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Alpha bloggers
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="flickr_pagination">
      <%= will_paginate @users, :container => false %>
    </div>
  </div>
  
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user%>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %> 
              <% if user == current_user %>
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "delete profile", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %> 
  <div class="row justify-content-md-center">
    <div class="flickr_pagination mb-4">
      <%= will_paginate @users, :container => false %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- Page Header -->
<header class="masthead" style="height:60px; background-image:url(<%= asset_path 'articles-bg.jpg' %>)">
  <div class="overlay" >
  </div>
</header>

<div class="container">
<%= render 'layouts/msg'%>
    <div class="row justify-content-md-center">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= @user.username %>´s profile
          </div>
          <div class="card-body">
            <%= gravatar_for @user, size: 200 %>
          </div>
          <div class="card-footer text-muted">
            <% if logged_in? && @user == current_user%>
              <%= link_to 'Edit your profile', edit_user_path(@user), class: 'btn btn-outline-info' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
      <div class="col-5 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            Articles
          </div>
        </div>
      </div>
    </div>

  <div class="row justify-content-md-center">
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
  <%= render 'articles/article'%>
  <div class="row justify-content-md-center">
    <div class="flickr_pagination mb-4">
      <%= will_paginate @articles, :container => false %>
    </div>
  </div>
</div>